apiVersion: backstage.io/v1alpha1
kind: DataProduct
metadata:
  name: "hello-react-app"
  description: "abcd123"
  annotations:
    github.com/project-slug: Manish3323/hello-react-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "team-d"
  consumesApis:
    - api:spotify
    - api:petstore
  providesApis:
    - api:streetlights
