# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Techdocs CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v3.1.2
    
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "16.x"
        registry-url: "https://registry.npmjs.org"
    - name: install packages
      run: |
        npm install -g @techdocs/cli
        pip install mkdocs-techdocs-core==1.*
    - name: generate docs
      run: techdocs-cli generate --no-docker
    - name: publish docs
      run: techdocs-cli publish --publisher-type azureBlobStorage --storage-name 'backstage' --entity default/Dataproduct/DataProduct1 --azureAccountName  ${{ secrets.AZURE_ACCOUNT_NAME }} --azureAccountKey  ${{ secrets.AZURE_ACCOUNT_KEY }}
